name: Release
on:
  workflow_dispatch:
jobs:
  package:
    uses: ./.github/workflows/reusable-package.yml
    secrets: inherit
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create release
        run: |
          imagetag=$(cat artifacts/imagetag.txt)
          tag="${imagetag#base-}"
          gh release create "${tag}" \
            --notes "Arch Linux WSL modern distribution based on the Docker image \`archlinux:${imagetag}\`" \
            ./artifacts/archlinux.wsl \
            ./artifacts/DistributionInfo.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
