name: Reusable package
on:
  workflow_call:
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build image
        run: |
          docker build -t archwsl .
          docker run --name archwsl -t archwsl ls
          docker export archwsl > install.tar
          gzip install.tar
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: install.tar.gz
          if-no-files-found: error
  build:
    needs: image
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Create image directory
        shell: pwsh
        run: |
          New-Item -Path . -Name x64 -ItemType Directory
          Copy-Item -Path image\install.tar.gz -Destination x64
      - name: Copy certificate
        shell: pwsh
        env:
          PFX: ${{ secrets.PFX }}
        run: |
          $pfxbin = [System.Convert]::FromBase64String($env:PFX)
          Set-Content -Path DistroLauncher-Appx/DistroLauncher-Appx_TemporaryKey.pfx -Value $pfxbin -AsByteStream
      - name: Update thumbprint
        shell: pwsh
        run: |
          $thumbprint = (Get-PfxCertificate -FilePath .\DistroLauncher-Appx\DistroLauncher-Appx_TemporaryKey.pfx).Thumbprint
          (Get-Content -Path .\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj) -creplace '(<PackageCertificateThumbprint>).*(</PackageCertificateThumbprint>)', ('$1' + $thumbprint + '$2') > .\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj
      - name: Update version
        shell: pwsh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
        run: |
          curl --version
          $request = "{ ""username"": ""$env:DOCKER_HUB_USERNAME"", ""password"": ""$env:DOCKER_HUB_PAT"" }"
          $token = (Invoke-RestMethod -Uri https://hub.docker.com/v2/users/login -Method Post -Headers @{ 'Content-Type' = 'application/json' } -Body $request).token
          $images = Invoke-RestMethod -Uri https://hub.docker.com/v2/namespaces/archlinux/repositories/archlinux/images?ordering=-last_activity -Method Get -Headers @{ "Authorization" = "Bearer $token" }
          $images.results | ForEach-Object { $item = $_; $_.tags | ForEach-Object { if ($_.tag -eq "latest" -and $_.is_current -eq "True") { $tags = $item; break } }; if (Test-Path variable:tags) { break } }
          $imagebuild = ($tags | Where-Object { $_.tag -like "base-*" }).tag.split(".")[-1]
          $version = "1." + [System.Text.Encoding]::UTF8.GetString($imagebuild[0..($imagebuild.Length - 5)]) + "." + [System.Text.Encoding]::UTF8.GetString($imagebuild[-4..-1])
          (Get-Content -Path .\DistroLauncher-Appx\MyDistro.appxmanifest) -creplace '(\bVersion=)"[\d.]+"', ('$1"' + $version + '"') > .\DistroLauncher-Appx\MyDistro.appxmanifest
      - name: Build
        shell: pwsh
        run: .\build.bat rel
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: x64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_*\DistroLauncher-Appx_*_x64.msixbundle
          if-no-files-found: error
