name: Reusable package
on:
  workflow_call:
    secrets:
      DOCKER_HUB_PAT:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        env:
          DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          ./build
          gzip --best archlinux.wsl
          sha256=$(sha256sum archlinux.wsl.gz)
          read -r sha256 _ <<<"${sha256}"
          tag=$(cat imagetag.txt)
          version="${tag#base-}"
          cat <<EOF >DistributionInfo.json
          {
            "ModernDistributions": {
              "Arch-Linux-Unofficial": [
                {
                  "Name": "Arch-Linux-Unofficial-${tag}",
                  "Default": true,
                  "FriendlyName": "Arch Linux Unofficial version ${version} (latest)",
                  "Amd64Url": {
                    "Url": "https://github.com/DevelopersCommunity/archlinux-wsl/releases/download/${version}/archlinux.wsl.gz",
                    "Sha256": "${sha256}"
                  }
                }
              ]
            }
          }
          EOF
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            archlinux.wsl.gz
            imagetag.txt
            DistributionInfo.json
          if-no-files-found: error
